# Generated by Django 4.2.7 on 2024-03-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone_numder',
            new_name='phone_number',
        ),
    ]
